name: deploy

on:
  push:
    branches:
      - develop
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name : Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      
      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.SSH_ID }}
          password: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /var/www/ASKu-api
            git pull origin develop
            npm install
