name: deploy

on:
  push:
    branches:
      - develop
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name : Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      
      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP_TEST }}
          username: ${{ secrets.SSH_ID_TEST }}
          password: ddd
          port: ${{ secrets.REMOTE_SSH_PORT_TEST }}
          script: |
            cd /var/www/ASKu-api
            git reset --hard HEAD
            git pull origin develop
            npm install
            cd swagger
            sed -i 's|http://localhost:8080|http://118.67.130.57:8080|g' swagger_output.json
            sed -i 's|http://localhost:8080|http://118.67.130.57:8080|g' swagger.js
